application: willcodeforfood
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /metronome\.js
  static_files: js/metronome.js
  upload: js/metronome\.js

- url: /metronomeworker\.js
  static_files: js/metronomeworker.js
  upload: js/metronomeworker\.js

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest
